# Numpy

NumPy — это расширение языка Python, добавляющее поддержку больших многомерных массивов и матриц, вместе с большой библиотекой высокоуровневых математических функций для операций с этими массивами.

In [10]:
import numpy as np   # подключение модуля numpy как np

## Массивы (Arrays)

Массивы схожи со списками в python, исключая тот факт, что элементы массива должны иметь одинаковый тип данных, как float и int. С массивами можно проводить числовые операции с большим объемом информации в разы быстрее и, главное, намного эффективнее чем со списками. 

Создание массива:

In [36]:
a = np.array([1, 4, 5, 8], float) # функция array принимает два аргумента:
print(a)                          # список для конвертации в массив .
print(type(a))                    # и тип для каждого элемента

[1. 4. 5. 8.]
<class 'numpy.ndarray'>


Ко всем элементам можно получить доступ и манипулировать ими также, как вы бы это делали с обычными списками:

In [12]:
a[:2] # индекс :2 , означает все элементы с начала до 2(не включая 2)

array([1., 4.])

In [13]:
a[3]

8.0

In [14]:
print(a)
a[0] = 5
print(a)

[1. 4. 5. 8.]
[5. 4. 5. 8.]


Массивы так же могут быть и многомерными

Пример двумерного массива:

In [17]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print(a)

print(a[0,1])
print(a[1,:]) # вся 2 строка

[[1. 2. 3.]
 [4. 5. 6.]]
2.0
[4. 5. 6.]


### Методы работы с массивами

In [18]:
a.shape # возвращает количество строк и столбцов

(2, 3)

In [19]:
a.dtype # возвращает тип элементов массива

dtype('float64')

Массивы можно переформировать при помощи метода, который задает новый многомерный массив. 

Следуя следующему примеру, мы переформатируем одномерный массив из десяти элементов во двумерный массив, состоящий из пяти строк и двух столбцов:

In [20]:
a = np.array(range(10), float) 
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
a = a.reshape(5, 2) # данный метод меняет массив в двумерный с 5 строками и 2 столбцами

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

### Математические операции

Когда для массивов мы используем стандартные математические операции, должен соблюдаться принцип: элемент--элемент. 

Это означает, что массивы должны быть одинакового размера во время сложения, вычитания и тому подобных операций:

In [38]:
a = np.array([1,2,3])
b = np.array([5,2,6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[6 4 9]
[-4  0 -3]
[ 5  4 18]
[0.2 1.  0.5]


Для двухмерных массивов, умножение остается поэлементным и не соответствует умножению матриц. 

Для этого существуют специальные функции, которые мы изучим позже.

In [28]:
a = np.array([[1,2], [3,4]], float)
b = np.array([[2,0], [1,3]], float)

a * b

array([[ 2.,  0.],
       [ 3., 12.]])